version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ivy-winter
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
  web:
    build: ./app
    command: ["go", "run", "app/main.go"]
    volumes:
      - .:/go/src/github.com/enpitut2018/IvyWestWinterServer
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
