version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ivy-winter
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
  web:
    build: ./app/.
    # command: "ls"
    command: ["go", "run", "github.com/enpitut2018/IvyWestWinterServer/app/main.go"]
    volumes:
      - /Users/user/go/src:/go/src
    ports:
      - 8080:8080
    depends_on:
      - db
